@Gateway_HostAddress = https://localhost:5211

### Register
POST {{Gateway_HostAddress}}/api/auth/register
Content-Type: application/json

###

### Login
POST {{Gateway_HostAddress}}/api/Token
Content-Type: application/json

###

### Movies (JWT gerekli)
GET {{Gateway_HostAddress}}/Movies
Authorization: Bearer
Accept: application/json

###